language: node_js
node_js: stable
# $: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm start

after_script:
  - cd ../
  - git clone "https://${GH_TOKEN}@${GH_REF}" blog
  - cp -rf CsdnSyncHexo/_posts/. ./blog/source/_posts
  - cd blog
  - git remote set-url origin --add "https://kongzifan:${CO_TOKEN}@${CO_REF}"
  - git add ./source/_posts/.
  - git commit -m "同步csdn博客"
  - git push

branches:
  only:
    - master

env:
 global:
   # Github
   - GH_REF: github.com/kongzf/blog.git
   # Coding
   - CO_REF: git.dev.tencent.com/kongzifan/blog-dev.git
