language: node_js
node_js: stable
# $: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm start

after_script:
  - git config user.name "kongzifan"
  - git config user.email "kongzf@126.com"
  - git clone git@github.com:kongzf/blog.git kongzf/blog
  - cp -r blog/source/_posts/. ./kongzf/blog/source/_posts
  - git add ./kongzf/blog/source/_posts/.
  - git commit -m "同步csdn博客"
  - git push
